.TH VDETERM 1 "July 29, 2008" "Virtual Distributed Ethernet"
.SH NAME
vdeterm \- (simple) Remote terminal for vde management sockets
.SH SYNOPSIS
.B vdeterm 
.I socket  
.br
.SH DESCRIPTION
A
\fBvdeterm\fP 
is a terminal application for a vde tools stream socket.

It has been created as a part of the vde-2 project: it is used as a remote 
console for vde_switch or for the wirefilter application.

vdeterm provides command editing, history of previous commands, command completion.
Debug asynchronous messages do not interfere with the command editing line.

.SH NOTICE
Virtual Distributed Ethernet is not related in any way with
www.vde.com ("Verband der Elektrotechnik, Elektronik und Informationstechnik"
i.e. the German "Association for Electrical, Electronic & Information
Technologies").

.SH SEE ALSO
\fBvde_switch\fP(1),
\fBwirefilter\fP(1).
.br
.SH AUTHOR
VDE is a project by Renzo Davoli <renzo@cs.unibo.it>
