.TH VDE_SWITCH 1 "December 6, 2006" "Virtual Distributed Ethernet"
.SH NAME
vde_switch \- Virtual Distributed Ethernet switch
.SH SYNOPSIS
.B vde_switch 
[ 
.B \-hub  
] 
[ 
.BI \-sock 
.I commdirpath  
]  
[ 
.BI \-mod 
.I octal-mode  
]  
[ 
.BI \-group
.I NAME
]  
[ 
.BI \-tap 
.I interface  
] 
[
.BI \-daemon 
]
.br
.SH DESCRIPTION
A
\fBvde_switch\fP 
is a virtual switch for the vde architecture.
.br
A vde network can include several vde_switches running on different
(real) computers.
vde_switches can be connected by vde cables (see
\fBvde_plug (1)\fP
).
.br
Supported architecture for VDE end nodes include: 
real linux boxes (through the tuntap interface),
bochs, qemu and MPS virtual machines.
.br
VDE is useful to create networks of heterogeneous virtual machines as
well as as a general tunneling tool -- all the ethernet based protocols work
by this kind of tunnel -- and also as a tool for mobility.
In fact VDE creates an overlay network where users can keep their IP
addresses despite of the change of IP addresses on the interfaces.

vde_switch needs root privileges to open a tap interface, can be run by
users when no -tap option is specified.

vde-2 has several features: VLAN, Fast Spanning Tree Protocol, command line management
(on console for foreground swithces, on a terminal for deamonized switches).
If a vde_switch run in foreground mode simply type return to have the prompt.
For daemons there is the -M option to specify the management socket. Unixterm is the tool
to start a terminal for the management.
Type "help" at the promt for a list of possible options.

.SH OPTIONS
.TP
.B \-hub, 
turn off the switch engine. It operates as a hub.
.TP
.B \-sock "\fIcommdirpath\fP"
specify the directory when comm socket are created.
The default value is "/tmp/vde.ctl"
.TP
.B \-mod "\fIoctalmode\fP"
specify the octal permissions for the comm sockets.
.TP
.B \-group "\fINAME\fP"
specify the group owner for the comm socket.
The default value is the current user's primary group
.TP
.B \-tap "\fIinterface\fP" 
connect the specified tuntap interface to this vde_switch (needs root privileges)
It is possible to specify several tap interfaces, comma separated.
.TP
.B \-daemon
Run as a daemon. Use syslog for logging.
.TP
.B \-f rcfile
rc file to set the initial switch configuration. This rc file has the same syntax of
the command line interface.
.TP
.B \-h 
help. please use it for a more complete list of options.
vde_switch is a modular program, options vary depending of the compiled-in modules.
.SH NOTICE
Virtual Distributed Ethernet is not related in any way with
www.vde.com ("Verband der Elektrotechnik, Elektronik und Informationstechnik"
i.e. the German "Association for Electrical, Electronic & Information
Technologies").

.SH SEE ALSO
\fBvde_plug\fP(1),
\fBvde_plug2tap\fP(1),
\fBvdeq\fP(1),
\fBdpipe\fP(1),
\fBunixterm\fP(1).
.br
.SH AUTHOR
VDE is a project by Renzo Davoli <renzo@cs.unibo.it>
.br
VDE started as an enhancement of uml_switch by Jeff Dike and others.
VDE-2 has been almost completely rewritten but maybe some statements
come from the historical source. So, some copyright and thanks also for Dike&Co.
